name: boden-build-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Boden Repo
        run: git clone --recurse-submodules https://github.com/AshampooSystems/boden.git
        
      - name: Generate and Open an IDE Project
        run: cd boden && python boden.py new -n AwesomeApp 
        
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.19.x'
          
      - name: Setup Gradle and init
        uses: gradle/gradle-build-action@v2
        with:
          arguments: wrapper
          gradle-version: 5.3.1
          build-root-directory: boden/AwesomeApp
          
      - name: Setup Gradle and init
        uses: gradle/gradle-build-action@v2
        with:
          arguments: init
          gradle-version: 5.3.1
          build-root-directory: boden/AwesomeApp
          
      - name: Setup Gradle and init
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: 5.3.1
          build-root-directory: boden/AwesomeApp
          
      - name: Build
        run: cd boden/AwesomeApp && gradlew.bat && python ../boden.py build -p android -t AwesomeApp && dir   # echo "C:\Users\runneradmin\gradle-installations\installs\gradle-5.3.1\bin\" >> $GITHUB_PATH &&
        
