name: boden-build-actions-workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Clone the Boden Repo
        run: git clone --recurse-submodules https://github.com/AshampooSystems/boden.git
        
      - name: Generate and Open an IDE Project
        run: cd boden && python boden.py new -n AwesomeApp 
        
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Execute Gradle build
        run: cd boden && cd AwesomeApp && ./gradlew build && dir
        
        
        
        
        
